### ISSUE TITLE
Rules for comments

### ISSUE THREAD

**Issue by iamjoshellis** [wearelighthouse/scss#4]
https://github.com/wearelighthouse/scss-lint/edit/feature-readme/README.md#L99

**Comment by cjquinn** [comment]
Just to bring the chat in her:

**josh**

> I pretty much do the same across php, js and css

**christy**

> Well thats probably the key point

**russell**

> Fine with the php one tbh

So in conclusion, we can use both types of comments:

`// for explanations`

```
/**
 * For documentation
 */
```
