### ISSUE TITLE
Specify max slector depth (if any) and BEM depth

### ISSUE THREAD

**Issue by iamjoshellis** [wearelighthouse/scss#9]
https://github.com/wearelighthouse/scss-lint/edit/feature-readme/README.md#L156

**Comment by RussellBishop** [comment]
This one is trickier for me - I'm treating these lints as unbreakable rules, and I think in some cases you might just have to get a nest depth of 4.

It probably won't be your favourite bit of code either, but if you're writing it, you're probably unable to get around it.

Thoughts?

Just trying out this 'style' thing - see if you can make it more 'warning' than 'invalid'.

**Comment by iamjoshellis** [comment]
You can specify the severity of each rule in the config file, see:
https://github.com/sasstools/sass-lint/tree/master#rules
